swagger: "2.0"
info:
  description: "Employee Example"
  version: "1.0"
  title: "Employee-api"
basePath: "/employee-service"
schemes:
- "http"
# format of bodies a client can send (Content-Type)
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: Authorization
paths:
 /login/{name}:
    get:
      tags:
       - "login details"
      summary: "Get login details from signed user"
      description: "Get Details from signed user"
      operationId: "getloginDetails"
      produces:
      - "application/json"
      parameters:    
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "A json of type for given signin id."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/login"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "loginService"  
  
 /signup:
    post:
      tags:
      - "signupDetails"
      summary: "Creates signupdetails."
      description: "Creates signupdetails."
      operationId: "createSignup"
      produces:
      - "application/json"
      parameters:    
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/signup"
      responses:
        200:
          description: "Signup Details"
          schema:
            type: "object"
            properties: {}
        400:
          description: "Error creating a signup details"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "signupService"
    get:
      tags:
       - "signup details"
      summary: "Get details"
      description: "Get Details by"
      operationId: "getsignupDetails"
      produces:
      - "application/json"
      responses:
        200:
          description: "A json of type for given signin id."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/signup"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "signupService"  
  
 /employee:
    post:
      tags:
      - "employeedetails"
      summary: "Creates employeedetails."
      description: "Creates employeedetails."
      operationId: "createEmployee"
      security: 
        - UserSecurity: []
      produces:
      - "application/json"
      parameters:    
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/employee"
      responses:
        200:
          description: "Employee Details"
          schema:
            type: "object"
            properties: {}
        400:
          description: "Error creating a Employee details"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "EmployeeService"
    get:
      tags:
       - "Employee details"
      summary: "Get details"
      description: "Get Details by"
      operationId: "getDetails"
      produces:
      - "application/json"
      security: 
        - UserSecurity: []
      responses:
        200:
          description: "A json of type for given employeeId."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/employee"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "EmployeeService"  
  
 /employee/{eId}:  
    get:
      tags:
      - "Employee  details by id"
      summary: "Get Details"
      description: "Get Details by employeeId"
      operationId: "getDetailsById"
      security: 
        - UserSecurity: []
      parameters:
        - name: eId
          in: path
          description: employeeId
          required: true
          type: string
      produces:
      - "application/json"
      responses:
        200:
          description: "A json of type for given employeeId."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/employee"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "EmployeeService" 
    delete:
      tags:
      - "Delete type by employee id"
      summary: "delete Details"
      description: "delete Details by employeeId"
      operationId: "deleteDetails"
      security: 
        - UserSecurity: []
      parameters:
        - name: eId
          in: path
          description: employeeId
          required: true
          type: string
      produces:
      - "application/json"
      responses:
        200:
          description: "deleted"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/employee"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "EmployeeService"     
    put:
      tags:
      - "update Details by Employeeid"
      summary: "updates a Details."
      description: "updates a Details."
      operationId: "updateDetails"
      security: 
        - UserSecurity: []
      parameters:
        - name: eId
          in: path
          description: employeeId
          required: true
          type: string 
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/employee"
      produces:
      - "application/json"
      responses:
        200:
          description: "update Details."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/employee"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "EmployeeService" 

 /swagger:
    x-swagger-pipe: swagger_raw
definitions:  
  employee:
   type: "object"
  signup:
    type: "object"
  login:
    type: "object"
